
const AUMENTAR_COUNT = 'AUMENTAR-COUNT';
const CAMBIAR_INTRUSTOR = 'CAMBIAR_INTRUSTOR';
const MODIFICAR_ALUMNOS = 'MODIFICAR_ALUMNOS';
const SUMAR_ALUMNOS = 'SUMAR_ALUMNOS';

module.exports = {
    AUMENTAR_COUNT,
    CAMBIAR_INTRUSTOR,
    MODIFICAR_ALUMNOS,
    SUMAR_ALUMNOS
}